name: google_maps_pro
description: A flutter plugin that provides latlong from postal code and reverse.
version: 0.1.4
homepage: https://github.com/ditheshthegreat/google_map_pro

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  flutter_json_view: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/google_logo.png

  plugin:
    platforms:
      android:
        package: com.dithesh.google_maps_pro
        pluginClass: GoogleMapsProPlugin
      ios:
        pluginClass: GoogleMapsProPlugin